# Generated by Django 6.0.2 on 2026-03-04 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAdvisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], max_length=50)),
                ('primary_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('secondary_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rent_mortgage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_premiums', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subscriptions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_loans', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variable_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('property_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('goals', models.TextField(blank=True)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_advisor',
                'ordering': ['-created_at'],
            },
        ),
    ]
